# Generated by Django 4.2.30 on 2026-08-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "jitsi_room",
                    models.CharField(
                        blank=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canaux_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        blank=True, related_name="canaux", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal",
                "verbose_name_plural": "Canaux",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="MessageCanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField(blank=True)),
                (
                    "fichier_joint",
                    models.FileField(
                        blank=True, null=True, upload_to="canaux/pieces_jointes/"
                    ),
                ),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_canaux",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.canal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de canal",
                "verbose_name_plural": "Messages de canal",
                "ordering": ["date_envoi"],
            },
        ),
    ]
