# Generated by Django 4.2.30 on 2026-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_canal_messagecanal"),
    ]

    operations = [
        migrations.AddField(
            model_name="canal",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="canaux/photos/"),
        ),
    ]
