# Generated by Django 4.2.30 on 2026-08-24 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0003_canal_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecanal",
            name="duree_secondes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagecanal",
            name="supprime_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages_canal_masques",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagecanal",
            name="supprime_pour_tous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagecanal",
            name="type_message",
            field=models.CharField(
                choices=[("texte", "Texte"), ("vocal", "Message vocal")],
                default="texte",
                max_length=10,
            ),
        ),
    ]
