# Generated by Django 4.2.30 on 2026-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cotisationmensuelle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresfinanciers',
            name='lien_paiement_wave',
            field=models.URLField(blank=True, help_text='Lien Wave utilisé par les membres pour payer leur cotisation (Barkelou)'),
        ),
    ]
