# Generated by Django 6.0.1 on 2026-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_parametresfinanciers_lien_paiement_wave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_transaction",
            field=models.CharField(
                choices=[
                    ("cotisation", "Cotisation Mensuelle"),
                    ("levee_fonds", "Levée de Fonds"),
                    ("don", "Don"),
                    ("depense", "Dépense"),
                    ("hadiya", "Hadiya"),
                    ("autre", "Autre"),
                ],
                max_length=50,
            ),
        ),
    ]
