# Generated by Django 6.0.1 on 2026-02-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role_max_length'),
        ('organisation', '0003_famille_regroupement_section_soussection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dahira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='organisation.dahira'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='regroupement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='organisation.regroupement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='organisation.section'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sous_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='organisation.soussection'),
        ),
    ]
