# Generated by Django 6.0.1 on 2026-02-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_dahira_customuser_regroupement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau_majalis',
            field=models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niveau_quran',
            field=models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20),
        ),
    ]
