# Generated by Django 6.0.1 on 2026-07-07 15:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_niveau_majalis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annee_naissance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='montant_cotisation',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Montant de la cotisation mensuelle assignée à ce membre', max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro de carte d'identité"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero_carte',
            field=models.CharField(blank=True, help_text='Numéro de carte membre', max_length=50),
        ),
    ]
