# Generated by Django 6.0.1 on 2026-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_annee_naissance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Super Admin (Programmeur / Auditeur / SAN)"),
                    (
                        "national_lecture",
                        "Administrateur / SG National (lecture seule globale)",
                    ),
                    (
                        "secretariat_national",
                        "Secrétariat National Administratif (lecture seule)",
                    ),
                    (
                        "finance_national",
                        "Secrétariat aux Finances National (lecture seule)",
                    ),
                    ("section_lecture", "Président / SG de Section (lecture seule)"),
                    (
                        "cellule_admin",
                        "Secrétaire Administratif de Cellule (écriture membres)",
                    ),
                    (
                        "cellule_finance",
                        "Secrétaire aux Finances de Cellule (écriture finance)",
                    ),
                    ("cellule_president", "Président de Cellule (lecture seule)"),
                    ("membre", "Membre"),
                ],
                default="membre",
                max_length=32,
            ),
        ),
    ]
