# Generated by Django 4.2.30 on 2026-08-22 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_reclasse_roles_jewrine"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("login_echec", "Échec de connexion"),
                            ("role_change", "Changement de rôle"),
                            ("membre_create", "Création d'un membre"),
                            ("membre_update", "Modification d'un membre"),
                            ("membre_delete", "Suppression d'un membre"),
                            ("import_excel", "Import Excel de membres"),
                            ("paiement_valide", "Validation de paiement(s)"),
                            (
                                "assignation_annuelle",
                                "Création d'une assignation annuelle",
                            ),
                            ("dahira_pilote", 'Statut "cellule pilote" modifié'),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cible_type",
                    models.CharField(
                        blank=True,
                        help_text="Ex: membre, cotisation, dahira",
                        max_length=50,
                    ),
                ),
                ("cible_id", models.IntegerField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_effectuees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal des Actions",
                "verbose_name_plural": "Journal des Actions",
                "ordering": ["-date_action"],
            },
        ),
    ]
