# Generated by Django 4.2.30 on 2026-08-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_journalaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="finance_ajout",
            field=models.BooleanField(default=False, verbose_name="Finance — Ajout"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="finance_lecture",
            field=models.BooleanField(default=False, verbose_name="Finance — Lecture"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="finance_modification",
            field=models.BooleanField(
                default=False, verbose_name="Finance — Modification"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="finance_suppression",
            field=models.BooleanField(
                default=False, verbose_name="Finance — Suppression"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="finance_validation",
            field=models.BooleanField(
                default=False, verbose_name="Finance — Validation"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membres_ajout",
            field=models.BooleanField(default=False, verbose_name="Membres — Ajout"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membres_lecture",
            field=models.BooleanField(default=False, verbose_name="Membres — Lecture"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membres_modification",
            field=models.BooleanField(
                default=False, verbose_name="Membres — Modification"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membres_suppression",
            field=models.BooleanField(
                default=False, verbose_name="Membres — Suppression"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="niveau_acces",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("section", "Section"),
                    ("cellule", "Cellule"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="synthese_nationale",
            field=models.BooleanField(
                default=False, verbose_name="Synthèse hiérarchique nationale"
            ),
        ),
    ]
