# Generated by Django 4.2.30 on 2026-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_backfill_permissions_from_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="logs_lecture",
            field=models.BooleanField(
                default=False,
                verbose_name="Logs système (connexions + journal des actions)",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="niveau_acces",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "National"),
                    ("regroupement", "Regroupement"),
                    ("section", "Section"),
                    ("cellule", "Cellule"),
                ],
                max_length=13,
            ),
        ),
    ]
