# Generated by Django 6.0.1 on 2026-02-25 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_materiel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Regroupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Regroupement',
                'verbose_name_plural': 'Regroupements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Sénégal', max_length=100)),
                ('regroupement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organisation.regroupement')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['nom'],
                'unique_together': {('regroupement', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='SousSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('H', 'Hommes'), ('F', 'Femmes')], max_length=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_sections', to='organisation.section')),
            ],
            options={
                'verbose_name': 'Sous-section',
                'verbose_name_plural': 'Sous-sections',
                'unique_together': {('section', 'sexe')},
            },
        ),
        migrations.CreateModel(
            name='LienFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('enfant', 'Enfant'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='organisation.famille')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_familiaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien familial',
                'verbose_name_plural': 'Liens familiaux',
                'unique_together': {('famille', 'membre')},
            },
        ),
        migrations.CreateModel(
            name='Dahira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('sous_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dahiras', to='organisation.soussection')),
            ],
            options={
                'verbose_name': 'Dahira',
                'verbose_name_plural': 'Dahiras',
                'ordering': ['nom'],
                'unique_together': {('sous_section', 'nom')},
            },
        ),
    ]
