# Generated by Django 6.0.1 on 2026-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0005_default_dahiras_all_soussections"),
    ]

    operations = [
        migrations.AddField(
            model_name="dahira",
            name="est_pilote",
            field=models.BooleanField(
                default=False,
                help_text="Cellule pilote : seules ces cellules sont visibles par les rôles nationaux/section durant la phase pilote.",
            ),
        ),
    ]
