# Generated by Django 4.2.30 on 2026-08-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("categorie", models.CharField(blank=True, max_length=100)),
                ("fichier", models.FileField(upload_to="documents/%Y/%m/")),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("image", "Image"),
                            ("excel", "Excel"),
                            ("word", "Word"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "taille_octets",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "ajoute_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_ajoutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
